import React from 'react';
import './sections.css';


const TermsServiceSection = () => {





    return (
        <div className="privacypolicystart">
            <div className="content-start">
                <h2 className="sec-heading">Terms of Service</h2>
                <div className="section-div">
                    <p className="sec-subheading">Introduction</p>

                    <p className="sec-para">
                        This document is an electronic record in terms of Information
                        Technology Act, 2000 and rules there under as applicable and the
                        amended provisions pertaining to electronic records in various statutes
                        as amended by the Information Technology Act, 2000. This electronic
                        record is generated by a computer system and does not require any
                        physical or digital signatures.
    </p>
                    <p className="sec-para">REEFLIX
                    ENTERTAINMENT
                    PRIVATE
                    LIMITED,
                    a
                    company
                    incorporated under the Companies Act, 2013, having its registered
                    office at 51/1, K. M. Naskar Road, P.S. – Regent Park, Kolkata –
                    700040, West Bengal, India, owns the domain name www.reeflix.com
                    (“Website”). The Website allows, upon subscription and payment of
                    necessary subscription fee, users to access and view, inter alia, movies
                    and TV serials, music and videos (“Content”) streamed over the Internet
                    to certain Internet-connected TVs, desktops, laptops, mobiles and other
devices.</p>
                    <p className="sec-para">The use of the Website and services and tools are governed by the
                    following terms and conditions, “Terms of Use” as applicable to the
                    Website including the applicable policies which are incorporated herein
                    by way of reference. If you transact on the Website and user interfaces,
                    you shall be subject to the policies that are applicable to the Website
                    and user interfaces, for such transaction. By mere use of the Website
                    and user interfaces, you shall be contracting with Reeflix and these
                    terms and conditions including the policies constitute your binding
obligations.</p>
                    <p className="sec-para">For the purpose of these Terms of Use, wherever the context so requires
                    “You”, “Your” or “User” shall mean any natural or legal person who has
                    agreed to become a member on the Website and user interfaces, by
                    providing certain information (as detailed in the Privacy Policy) while
registering on the Website and user interfaces.</p>
                    <p className="sec-para">BY ACCEPTING THESE TERMS OF USE IN ANY MANNER OR
                    ACCESSING THIS WEBSITE AND USER INTERFACES, YOU CONSENT,
                    AGREE AND UNDERTAKE TO ABIDE, BE BOUND BY AND ADHERE
                    TO THE TERMS OF USE and the Privacy Policy accessible at
                    www.reeflix.com/terms-of-use
                    and
                    www.reeflix.com/privacy-policy
                    respectively and any other terms which govern the Website and user
                    interfaces, AND IF YOU DO NOT AGREE TO THESE TERMS OF USE,
                    YOU ARE NOT ENTITLED TO AVAIL OF / USE THE SERVICES AND
ANY USE THEREAFTER SHALL BE UNAUTHORIZED.</p>

                </div>


                <p className="sec-subheading">DESCRIPTION OF SERVICES AND ACCEPTANCE OF TERMS OF
USE</p>
                <div className="section-div ">



                    <p className="sec-para">As stated above, Reeflix, through the Website and user interfaces,
                    allows, upon subscription and payment of necessary subscription fee,
                    access and view, inter alia, movies and TV serials, music and videos
                    (“Content”) streamed over the Internet to certain Internet-connected
TVs, desktops, laptops, mobiles and other devices.</p>

                    <p className="sec-para">Reeflix, inter alia, provides an online website www.reeflix.com as an
                    interactive platform for its viewers and any associated mobile sites,
                    applications to inter alia view films and web series - including trailers,
                    and music and video content including viewing schedules of content
                    offered etc. on the Website and user interfaces, and any other features,
                    tools, applications, materials, or other services offered from time to time
                    by Reeflix in connection with its business, provided on the Website and
                    user
                    interfaces,
                    “Content”
                    and
                    includes
                    posting
                    of
                    comments,
                    participation in contests (all such features of the Website and user
interfaces, collectively referred to as “Services”.</p>
                    <p className="sec-para">Content will be made available to you through different modes, at the
                    discretion of Reeflix, including via video on demand basis for viewing at
                    the User’s discretion at a time chosen by you and download for offline
                    viewing by you. Download for offline viewing is for App only. For the Content that will be made available to You, You will be granted a non-
                    exclusive,
                    non-transferable,
                    non-sub-licensable,
                    revocable
                    limited
                    license to view the Content for your personal, non-commercial viewing,
                    and that no right, title or interest in any Content will be deemed
                    transferred to You. Please note that both the availability and Your
                    ability to access the Content or some part of Services, (a) is subject to
                    Reeflix’s sole discretion and (b) may be dependent upon Your
                    geographical location and (c) is on the condition that not all Content or
                    Services will be available to all viewers. On account of the nature of the
                    Internet, this Website and the Content and Services may also be
                    accessed in various geographical locations; and You hereby agree and
                    acknowledge that You are accessing this Website and availing of the
                    Services, at Your own risk, choice and initiative and You agree and
                    undertake to ensure that Your use of the Website and user interfaces,
                    and the Services complies with all applicable laws including the local
                    laws in Your jurisdiction. Further, such Services and Content may vary
                    from place to place, time to time and device to device and would be
                    subject to various parameters such as specifications, device, Internet
                    availability and speed, bandwidth, etc. You agree and acknowledge that
                    Reeflix may monitor or use certain technologies for monitoring of
                    activities including logging of Your IP address to ascertain and verify
                    your geographical location. To facilitate Your viewership and access, the
                    Services can be packaged by Reeflix through different models such as,
                    Content or Services may be accessible (a) free of charge which may
                    include advertisements or commercials or (b) via subscription through
                    payment of a subscription fee with or without advertisements/
                    commercials or (c) a pay-per-view model with or without advertisements
                    /commercials or (d) with a combination of the foregoing on the Website.
                    The Services can be availed through platforms, software and devices,
                    which Reeflix approves from time to time, the current list for which is
                    as set out below “Compatible System”. In some cases, whether a device
                    is (or remains) a Compatible System may depend on software or
                    platform provided or maintained by the device manufacturer or other third parties. As a result, devices that are Compatible System at one
time may cease to be Compatible System in the future.</p>
                    <p className="sec-para">The Reeflix website works best with : </p>

                    <ol>
                        <li>Latest version of Google Chrome</li>
                        <li>Latest version of Firefox</li>
                        <li>Latest version of Safari</li>
                        <li>Latest version of Microsoft Edge</li>
                        <li>Microsoft Windows 10 or above</li>
                        <li>JavaScript and cookies enabled</li>
                    </ol>
                    <p className="sec-para">The Reeflix applications work best with a minimum system requirement
of : </p>

                    <ol>
                        <li>Android v.5.0 or above</li>
                        <li>iOS 9 or above</li>

                    </ol>
                    <p className="sec-para">Smart tv /firestick or any compactable upcoming technologies. </p>
                    <p className="sec-para">Participation in any contest and or game on the Website conducted by
                    Reeflix or viewing of certain Content may be subject to further terms
                    and conditions as may be notified by Reeflix from time to time on the
Website or otherwise. </p>

                </div>

                <div className="section-div ">


                    <p className="sec-subheading">SUBSCRIPTION SERVICES</p>

                    <p className="sec-para">Some of the Content made available on the Website can be availed only
                    by registered Users who have registered under a subscription model
                    (“Registered User”). You may need to register yourself on the Website
                    and user interfaces, to avail these services on a subscription model
                    (“Subscription”). To become a Registered User, You may be required to
                    provide certain personal information to Reeflix, including sensitive
                    personal data, and may be required to make payments “Subscription Fee” as per the applicable membership plan through a debit card, credit
                    card, internet banking or through, e-prepaid wallet or other payment
                    method accepted by Reeflix “Payment Method” that You opted for
                    during registration. Reeflix will be using third party payment gateways
                    to process and facilitate the payment of Your Subscription Fee to
                    Reeflix. On successful registration to the Subscription, Reeflix will
                    intimate you of the same through e-mail. Reeflix may offer different
                    kinds of Subscription plans, each of these Subscription plans being
                    subject to different limitations and restrictions and the cost of each of
                    these Subscription plans may vary.
                    Reeflix shall have the discretion to make certain content that is a part
                    of the Subscription available to you on more than one end user
                    Compatible System concurrently. Reeflix shall also have the discretion
                    to make certain Content that is a part of the Subscription available to
you on not more than one end user Compatibility System.</p>

                </div>

                <div className="section-div ">

                    <p className="sec-subheading">FREE TRIALS</p>

                    <p className="sec-para">Some of the Subscription plans may start with a free trial. The free trial
                    period may last for a period of seven (7) days or such other term as may
                    be determined by Reeflix. Your eligibility for a free trial including the
                    time for such free trial and the Content available to be viewed during
                    free trial period is at the discretion of Reeflix and such free trial can be
                    modified, suspended or terminated by Reeflix at any point of time
                    without giving notice to you. In case you are eligible for any free trial,
                    Reeflix may charge you a token amount of money at the time of your
                    registration for the Subscription plan. This token amount will be
                    refunded to you once Reeflix receives the confirmation from the third
                    party payment gateway provider that Your Payment Method has been
registered. </p>



                </div>

                <div className="section-div ">

                    <p className="sec-subheading">PAYMENTS</p>
                    <p className="sec-para">Reeflix will automatically start billing as per your selected Payment
                    Method for the Subscription plan elected by you at the time of
                    registration through the third party payment gateway at the end of the
                    free trial period, if applicable unless you cancel the Subscription before
                    the end of the free trial period. The cancellation of the Subscription can
                    be done through the “My Account” section of the Website. It may take a
                    few days for your payment made to Reeflix to be reflected in your “My
Account” section.</p>
                    <p className="sec-para">In case you cancel Your Subscription before the end of the free trial
                    period, you will not be entitled to any compensation monetary or
otherwise from Reeflix for the unutilized period of free trial.</p>
                    <p className="sec-para">You cannot change your Payment Method during the tenure of your
                    Subscription. If your selected Payment Method is no longer available or
                    expires or Your Payment Method fails for whatsoever reason, you will be
                    responsible and liable for any uncollected amounts and Reeflix reserves
the right to terminate the Subscription offered to you.</p>
                    <p className="sec-para">The Subscription Fee will be billed at the beginning of Your
                    membership or at the end of free trial period, as applicable and on each
                    subsequent renewal automatically (as per the Subscription plan chosen
                    by You) unless and until You cancel Your Subscription or the
                    Subscription is otherwise suspended or discontinued pursuant to these
                    Terms. To see the commencement date for your next renewal period or
                    to cancel your subscription to the Subscription, You need to visit the
                    “My Account” section on your profile page. On cancellation of
Subscription You will be notified by Reeflix.</p>
                    <p className="sec-para">Reeflix will be automatically billing as per Your Payment Method for
                    each Subscription period on a monthly basis. However, if you change
                    your membership plan, this could result in changing the day on which
you are billed and the amount which you are billed.</p>
                    <p className="sec-para">In case of change in the Subscription Fee for a particular membership
                    plan that is already opted by You, Reeflix will give you an advance
notice of these changes.</p>

                    <p className="sec-para">The Subscription Fees specified for each Subscription plan are
                    inclusive of applicable taxes. The Subscription Fees billed are non-
                    refundable irrespective of whether the Subscription has been availed by
you or not.</p>
                    <p className="sec-para">Any changes in the Subscription Plan opted by you is effective only
                    after the expiry of the current Subscription period for which you have
                    already been billed. Accordingly, the Subscription as per revised plan
                    opted by you shall be effective only after the expiry of the then current
Subscription period.</p>

                    <p className="sec-para">Any request for change or cancellation in any Subscription plan prior to
                    the expiration of the current Subscription plan period will not entail
                    you with a refund for any portion of the Subscription Fee paid by you
for the unexpired period.</p>

                    <p className="sec-para">You also understand and acknowledge that Reeflix only facilitates the
                    third party payment gateway for processing of payments. This facility is
                    managed by the third party payment gateway provider and you are
                    required to follow all the terms and conditions of such third party
payment gateway provider.</p>

                    <p className="sec-para">You are
                    responsible for the
                    information
                    provided
                    by
                    accuracy and authenticity of the
                    you,
                    including
                    the
                    bank
                    account
                    number/credit card details and the like. You agree and acknowledge
                    that Reeflix shall not be liable and in no way be held responsible for
                    any
                    losses
                    whatsoever,
                    whether
                    direct,
                    indirect,
                    incidental
                    or
                    consequential, including without limitation any losses due to delay in
processing of payment instruction or any credit card fraud.</p>

                    <p className="sec-para">You can access the status of Your Subscription anytime through the
“My Account” section on the “Settings” page.</p>

                    <p className="sec-para">You can file any complaint related to payment processing on the
                    Website or user interfaces, and the same will be forwarded to the
concerned third party payment gateway provider for redressal.</p>

                    <p className="sec-para">Upon payment through any of the payment modes, a confirmation of
                    receipt of such payment from the payment gateway provider, an invoice
                    will be made available to you, if applicable. Upon payment being
                    received by Reeflix through any of the payment method(s), Reeflix shall
                    make the Subscription available to you through any of the approved
modes of delivery that Reeflix adopts.</p>


                    <p className="sec-para">It is hereby clarified that the Subscription offered to you is by Reeflix
                    and not by any third party including any payment gateway service
providers.</p>

                    <p className="sec-para">Reeflix reserves the right to change, terminate or otherwise amend the
                    Subscription plans, Subscription Fees for the Subscription and billing
                    cycles at its sole discretion and at any time. Such amendments shall be
                    effective upon posting on the Website and your continued use of the
                    Service shall be deemed to be your conclusive acceptance of such
amendments.</p>

                    <p className="sec-para">Reeflix reserves the right to change, supplement, alter or remove any of
                    the Content that is subject to a Subscription Fee as it deems fit. Reeflix
                    does not guarantee the availability of a specific Content or a minimum
Content that is subject to a Subscription Fee.</p>

                    <p className="sec-para">Post-Cancellation of Your Subscription, if you wish to re-subscribe to
the Subscription, you may do so from the Website and user interfaces.</p>

                </div>


                <p className="sec-subheading">ELECTRONIC COMMUNICATIONS</p>

                <div className="section-div formulti-para">
                    <p className="sec-para">When you use/avail the Services or send any data, information or
                    communication to Reeflix, You agree and understand that you are
                    communicating with Reeflix through electronic media/records and you
                    consent to receive communications via electronic records from Reeflix periodically and as and when required. Reeflix will communicate with
                    you by email or any push or other message or electronic records on the
                    email address and or mobile number available with Reeflix or made
                    available to Reeflix through a partner which will be deemed adequate
service of notice / electronic record.</p>


                    <p className="sec-para">You give consent to Reeflix and / or its respective affiliates and
                    partners contacting you using the contact information you have
                    provided to Reeflix at any time during your association with Reeflix for
any purpose including but not limited to : </p>

                    <ol>
                        <li>To obtain feedback regarding the Service;</li>
                        <li>ITo contact you for offering new products or services, whether offered
by us, or our respective affiliates or partners.</li>

                    </ol>
                    <p className="sec-para">You acknowledge and agree that you may be contacted for the above
                    purposes, using any of the contact details provided by you, including
                    via emails, text messages or phone calls. In the event You have
                    indicated any “do not disturb” preferences to Your telecom service
                    provider, and registered Yourself on the national customer preference
                    register / “do not disturb”; or similar list, You are requested to ensure
                    that Your registered preferences allow for communications to be sent to
You in accordance with the above provisions. </p>
                    <p className="sec-para">The Content contained in the Services including but not limited to on
                    the Website is protected by copyright, trademark, patent, trade secret
                    and other laws, and shall not be used except as provided in these
Terms and Conditions, without the written permission of Reeflix.</p>
                </div>


                <p className="sec-subheading">USER COMMITMENTS</p>

                <div className="section-div ">



                    <p className="sec-para">By agreeing to use/avail the Services::</p>
                    <ul>
                        <li> You confirm that all the data and information supplied by you when
                        you register (“Registration Data”) and provided by you to Reeflix and or any Reeflix affiliates, distributors is true, current, complete and
accurate in all respects.</li>
                        <li> You agree to promptly update Your Registration Data so that your
information remains true, current, complete, and accurate at all times.</li>

                        <li>You acknowledge and agree that Your Registration Data and any other
                        personal data collected by Reeflix is subject to Reeflix’s Privacy Policy.
                        For more information, view the full Privacy Policy. Reeflix may collect
                        information such as occupation, language, PIN code, area code, unique
                        device identifier, location, and the time zone where the Services are
                        used and may use these to target advertising and make content
recommendations.</li>
                        <li>You acknowledge, consent and agree that Reeflix may access,
                        preserve, transfer and disclose Your account information and/or User
                        Material subject to the Privacy Policy, if required to do so by law to co-
                        operate with mandated government and law enforcement agencies or to
                        any private parties by an order under law for the time being in force to
                        enforce and comply with the law including to various tax authorities
                        upon any demand or request by them or in a good faith belief that such
                        access, preservation, or disclosure is reasonably necessary to: (a)
                        comply with legal process and/or any applicable law in the territory; (b)
                        enforce the Terms and Conditions; (c) respond to Your requests for
                        customer service; or (d) protect the rights, property or personal safety of
Reeflix, affiliates, its users and the public.</li>
                        <li>You agree that Reeflix has the right to temporarily suspend access to
                        the whole or any part of the Services for any technical/operational
                        reason and shall be under no liability to you in such an event. Reeflix
                        may, but shall not be obliged to, give you as much notice of any
                        interruption of access to the Services as is reasonably practicable.
                        Reeflix will restore access to the Services as soon as reasonably
practicable after temporary suspension.</li>
                        <li>You agree that Reeflix shall be under no liability whatsoever in the
                        event of non-availability of the Website or any portion thereof
                        occasioned by Act of God, war, disease, revolution, riot, civil
                        commotion, strike, lockout, flood, fire, satellite failure, failure of any
                        public utility, man-made disaster, satellite failure or any other cause
whatsoever beyond the control of Reeflix.</li>
                        <li>You acknowledge and agree not to either directly or through the use of
                        any device, software, internet site, web-based service, or other means
                        remove, alter, bypass, avoid, interfere with, violate, or circumvent any
                        patent; trade secret; copyright, trademark, or other proprietary notice
                        marked on the Content or any digital rights management mechanism or
                        device; any content protection or access control measure associated
                        with
                        the
                        Content,
                        including
                        geo-filtering
                        mechanisms;
                        privacy;
publicity; or other proprietary right under applicable law.</li>
                        <li>You agree not to either directly or through the use of any device,
                        software, internet site, web based service, or other means copy,
                        download, capture, reproduce, duplicate, archive, distribute, upload,
                        publish, modify, translate, broadcast, perform, display, sell, transmit or
                        retransmit the Content or create any work or material that is derived
                        from or based on the Content. This prohibition applies regardless of
                        whether such derivative works or materials are sold, bartered, or given
away.</li>
                        <li>You agree that Reeflix and/or its affiliates own and/or retains all
                        rights to the Services and the Content throughout the territory of the
                        world in perpetuity. You further agree that the Content You access and
                        view as part of the Services is owned or controlled by Reeflix, its
                        affiliates and or its licensors. The Services and the Content are
                        protected by copyright, trademark, trade secret, and other intellectual
property laws.</li>
                        <li>Except as provided in these Terms of Use (or otherwise expressly
                        provided by Reeflix), You may not copy, download, screen capture, reproduce, duplicate, archive, upload, modify, translate, publish,
                        broadcast, transmit, retransmit, distribute, perform, display, sell, frame
                        or deep-link, make available, or otherwise use any Content contained in
the Services. You further agree not to use the Services to:</li>
                        <p className="sec-para">Post, upload or otherwise transmit or link to Content that is: unlawful;
                        threatening; abusive; obscene; vulgar; sexually explicit; pornographic or
                        inclusive of nudity; offensive; excessively violent; invasive of another’s
                        privacy, publicity, contract or other rights; tortious; false or misleading;
defamatory; libelous; hateful; or discriminatory;</p>
                        <p className="sec-para">Harass or harm another person;</p>

                        <p className="sec-para">Exploit or endanger a minor; Impersonate or attempt to impersonate
any person or entity;</p>

                        <p className="sec-para">Violate any patent, trademark, trade secret, copyright, privacy,
publicity or other proprietary right;</p>

                        <p className="sec-para">Introduce or engage in activity that involves the use of viruses, software
                        disabling codes, bots, worms, or any other computer code, files or
                        programs that interrupt, destroy, or limit the functionality of any
                        computer software or hardware or telecommunications equipment, or
                        otherwise permit the unauthorized use of or access to a computer or a
computer network;</p>

                        <p className="sec-para">Attempt to decipher, decompile, disassemble or reverse-engineer any of
                        the software, applications and/or any element comprising the Website,
the application for accessing the Content, or the Reeflix Services;</p>

                        <p className="sec-para">Interfere with, damage, disable, disrupt, impair, create an undue
                        burden on, or gain unauthorized access to the Reeflix Services,
                        including Reeflix Entertainment Private Limited’s servers, networks or
                        accounts; Cover, remove, disable, manipulate, block or obscure
                        advertisements or other portions of the Content; Delete or revise any
information provided by or pertaining to any other user of Reeflix.</p>

                        <p className="sec-para">Further, You agree not to Use technology or any automated system
                        such as scripts, spiders, offline readers or bots in order to collect or
                        disseminate usernames, passwords, email addresses or other data from
                        Reeflix, or to circumvent, delete, deactivate, decompile, reverse
                        engineer, disassemble or modify any security technology or software
that is part of the Reeflix or the Website;</p>

                        <p className="sec-para">Send or cause to send (directly or indirectly) unsolicited bulk messages
                        or other unsolicited bulk communications of any kind through Reeflix.
                        If you do so, you acknowledge you will have caused substantial harm to
                        Reeflix, but that the amount of harm would be extremely difficult to
                        measure. As a reasonable estimation of such harm, and by way of
                        liquidated damages and not as a penalty, You agree to pay Reeflix INR
                        1000 (Indian Rupees One Thousand only) for each actual or intended
                        recipient of such communication without prejudice to any other rights
of action that Reeflix may have against You in law or equity;</p>

                        <p className="sec-para">Solicit, collect or request any personal information for commercial or
unlawful purposes;</p>

                        <p className="sec-para">Engage
                        in
                        commercial
                        advertisements
                        or
                        activity
                        solicitations
                        (including
                        of
                        but
                        business;
                        not
                        sales;
                        limited
                        to
                        contests;
                        sweepstakes; creating, recreating, distributing or advertising an index
                        of any significant portion of the Content; or building a business using
                        the Content) without Reeflix Entertainment Private Limited’s prior
written consent;</p>

                        <p className="sec-para">Use technology or other means to access, index, frame, or link to the
Website (including the Content) that is not authorized by Reeflix;</p>

                        <p className="sec-para">Access the Website (including the Content) through any automated
                        means, including “robots”, “spiders”, “offline readers” (other than by
                        individually performed searches on publicly accessible search engines
                        for the sole purpose of, and solely to the extent necessary for, creating
                        publicly available search indices – but not caches or archives – of the Website and excluding those search engines or indices that host,
promote, or link primarily to infringing or unauthorized content);</p>

                        <p className="sec-para">Use the Services to advertise or promote competing services;</p>

                        <p className="sec-para">Use the Services in a manner inconsistent with any and all applicable
law;</p>

                        <p className="sec-para">Attempt, facilitate, induce, aid and abet, or encourage others to do any
of the foregoing.</p>
                        <ol>
                            <li>You agree that your use of the Services and the Content may give you
                            the opportunity to view, publish, transmit, submit posts and/or
                            comment in accordance with these Terms and Conditions. You agree
                            that You will not misuse the Content and/or other user material You
                            access and view as part of the Service, including without limitation,
                            download/store
                            the
                            Content by illegal/non-permitted means, or
                            infringe any of Reeflix’s / or its licensor’s copyright, trademark, and
other intellectual property including any rights.</li>
                            <li>You further agree that You shall not post, publish, transfer, upload,
                            transmit or submit any of the Content, including without limitation
                            videos, images, comments, User Material (defined below) or articles, of
                            the Website on any other website, webpage or software, whatsoever
which is not owned by Reeflix.</li>
                            <li>You agree that the Content provided on the Website is strictly for Your
                            private viewing only and not for public exhibition irrespective of
                            whether the public is charged for such exhibition or not. You hereby
                            agree to refrain from further broadcasting or making available the
                            Content provided on the Website to any other person(s), or in any
manner communicate such Content to the public.</li>


                        </ol>



                    </ul>
                    <p className="sec-para">In case the Website allows You to download or stream any of the
                    Content therein, You agree that You will not use, sell, transfer or
                    transmit the Content to any person or upload the Content on any other
                    website, webpage or software, which may violate/cause damages or injuries to any rights of Reeflix or its affiliates or any third party
                    including privacy rights, publicity rights, and intellectual property
rights.</p>
                    <p className="sec-para">You may encounter third party applications while using the Website
                    including, without limitation, websites, widgets, software, services that
                    interact with the Website. Your use of these third party applications
                    shall be subject to such third party terms of use or license terms.
                    Reeflix shall not be liable for any representations or warranties or
                    obligations made by such third party applications to you under
contract or law.</p>

                </div>


                <p className="sec-subheading">TERMINATION OF SERVICE</p>
                <div className="section-div ">
                    <p className="sec-para">Reeflix reserves the right to immediately terminate, suspend, limit, or
                    restrict Your account or Your use of the Services or access to Content
                    at any time, without notice or liability, if Reeflix so determines in its
                    sole discretion, for any reason whatsoever, including that You have
                    breached these Terms of Use, the Privacy Policy, violated any law, rule,
                    or regulation, engaged in any inappropriate conduct, provided false or
                    inaccurate information, or for any other reason. You hereby agree and
                    consent to the above and agree and acknowledge that Reeflix can, in its
                    sole discretion, exercise its right in relation to any or all of the above,
                    and that Reeflix, its directors, officers, employees, affiliates, agents,
                    contractors, principals or licensors shall not be liable in any manner for
the same; and You hereby agree, acknowledge and consent to the same.</p>
                </div>

                <p className="sec-subheading">USER REVIEWS, COMMENTS AND OTHER MATERIAL</p>
                <div className="section-div ">
                    <p className="sec-para">You may have an opportunity to publish, transmit, submit, or
                    otherwise
                    post
                    (collectively,
                    “Post”
                    only
                    reviews
                    or
                    comments
                    (collectively, “User Material”). As it concerns User Material, without
                    prejudice to your obligation to otherwise comply with applicable laws during the course of using the Services, You agree to hereby comply
                    with any and all applicable laws, as well as any other rules and
restrictions that may be set forth herein or on the Website or Services.</p>

                    <p className="sec-para">You agree that Reeflix shall have the right but have no obligation, to
                    monitor User Material and to restrict or remove User Material that
                    Reeflix may determine, in its sole discretion, is inappropriate or for any
                    other reason. You acknowledge that Reeflix reserves the right to
                    investigate and take appropriate legal action against anyone who, in
                    Reeflix’s sole discretion, violates these Terms of Use, including, but not
                    limited to, terminating their account, terminate, suspend, limit, or use
                    of the Services or access to Content and/or reporting such User
                    Material, conduct, or activity, to law enforcement authorities, in
                    addition to any other available remedies under law or equity. In
                    addition to the restrictions set forth above, You must adhere to the
                    below terms and conditions and not host, display, upload, modify,
                    publish, transmit, update or share any information /material/User
Material that:</p>
                    <ul>
                        <li>belongs to another person and to which You do not have any right
to;</li>
                        <li>is grossly harmful, harassing, blasphemous, defamatory, obscene,
                        pornographic, pedophilic, libelous, invasive of another's privacy,
                        hateful, or racially, ethnically objectionable, disparaging, relating or
                        encouraging money laundering or gambling, or otherwise unlawful in
any manner whatsoever;</li>
                        <li>harms minors in any way;</li>
                        <li>infringes any patent, trademark, design, copyright or other
proprietary rights;</li>
                        <li>violates any law for the time being in force;</li>
                        <li>deceives or misleads the addressee about the origin of such
                        messages or communicates any information which is grossly offensive
or menacing in nature;</li>
                        <li>impersonates another person;</li>
                        <li>contains software viruses or any other computer code, files or
                        programs designed to interrupt, destroy or limit the functionality of any
computer resource;</li>
                        <li>threatens the unity, integrity, defense, security or sovereignty of
                        India, friendly relations with foreign states, or public order or causes
                        incitement to the commission of any cognizable offence or prevents
                        investigation of any offence or is insulting any other nation. You also
                        represent and warrant that the Posting of Your User Material does not
                        violate any right of any party, including privacy rights, publicity rights,
                        and intellectual property rights.




</li>

                    </ul>
                    <p className="sec-para">You acknowledge that the User Material is not confidential and that you
have no expectation of privacy in it.</p>
                    <p className="sec-para">By posting the User Material, You hereby grant Reeflix a license to use,
                    display, reproduce, distribute, modify, delete from, add to, prepare
                    derivative works of, publicly perform, and publish such User Material
                    worldwide, including on or through any property, in perpetuity, in any
                    media formats and any media channels now known or hereinafter
                    created. The license you grant to Reeflix is non-exclusive, royalty-free,
                    irrevocable, and sub licensable. Additionally, Reeflix is free to use any
                    ideas, concepts, know-how, or techniques contained within such User
                    Material for any purpose, including, but not limited to, developing,
                    manufacturing, marketing, and providing commercial products and
                    services, including the Services. Reeflix’s use of such User Material
                    shall not require any further notice of attribution to you and such use
                    shall be without requirement of any permission from or any payment to
                    you or any other person or entity. You hereby agree and confirm that the provisions of section 19(4) of the Indian Copyright Act, 1957, shall
not apply to this license.</p>

                    <p className="sec-para">In no event does Reeflix assume any responsibility or liability
                    whatsoever for any User Material, and You agree to waive any legal or
                    equitable rights or remedies you may have against Reeflix with respect
to such User Material.</p>

                    <p className="sec-para">If you have any complaints relating to any third party User Material or
                    Content
                    uploaded
                    on
                    the
                    Website,
                    then
                    please
                    contact:
                    reeflixtv@gmail.com, which must bear your digital signature or a signed
written complaint, should include the following information:</p>
                    <ul>
                        <li>Details Of The Objectionable User Material Or Content;</li>
                        <li>Details Of The Basis Of The Objection;</li>
                        <li>What Relief Is Being Requested;</li>
                    </ul>

                    <p className="sec-para">All Other Relevant Information Required By Reeflix Entertainment
Private Limited To Assess The Complaint.</p>

                    <p className="sec-para">Reeflix shall on examination of the complaint take all reasonable
                    measures, including taking down the objectionable User Material
                    expeditiously in accordance with applicable law. You agree and
                    acknowledge that Reeflix's responsibility in relation to objectionable
                    User Material is limited to removing them post receipt of your
                    objections in accordance with these Terms of Use and Reeflix shall not
                    be responsible or liable for any other damages or losses incurred by you
of any nature whatsoever.</p>

                </div>

                <p className="sec-subheading">LINKED DESTINATIONS AND ADVERTISING</p>
                <div className="section-div ">
                    <p className="sec-para">Part of this Website/Service contains advertising and other material
                    submitted to Reeflix by third parties and/or links to third party sites
                    and third party content. Although display of advertisements on the
                    Website on request is subject to Reeflix’s terms and conditions, Reeflix expressly disclaims any liability arising out of the usage or viewing of
                    these products or services advertised on the Website or the (third party)
                    content made available / hosted on the third party sites. You agree and
                    acknowledge that Reeflix does not endorse or sponsor such third party
                    sites, content, advertising or other material. This Website may contain
                    articles contributed by several individuals. The views are exclusively
                    their own and do not represent the views of Reeflix, affiliates and/ or its
                    management. All liability in respect of the above is excluded to the
                    extent permitted by law including any implied terms. Indian law and
                    jurisdiction applies with respect to contents of this Website. While
                    using this website for information purposes or otherwise, users
acknowledge and accept the above disclaimer.</p>

                    <p className="sec-para">If Reeflix provides links or pointers to other websites or destinations,
                    you should not infer or assume that Reeflix operates, controls, or is
                    otherwise connected with these other websites or destinations. When
                    you click on a link within the Services, Reeflix will not warn you that
                    you have left the Services and are subject to the terms and conditions
                    (including privacy policies) of another website or destination. In some
                    cases, it may be less obvious than others that you have left the Services
                    and reached another website or destination. Please be careful to read
                    the terms of use and privacy policy of any other website or destination
                    before you provide any confidential information or engage in any
                    transactions. You should not rely on these Terms and Conditions
                    and/or Privacy Policy to govern your use of another website or
destination..</p>

                    <p className="sec-para">Reeflix is not responsible for the content or practices of any website or
                    destination other than the Website, even if it links to the Website and
                    even if the website or destination is operated by a company affiliated or
                    otherwise
                    connected
                    with
                    Reeflix.
                    By
                    using
                    the
                    Services,
                    You
                    acknowledge and agree that Reeflix is not responsible or liable to you
                    for any content or other materials hosted and served from any website
                    or destination other than the Website. Reeflix takes no responsibility for advertisements or any third party material posted on the Website nor
                    does it take any responsibility for the products or services provided by
                    advertisers. Any dealings you have with advertisers found while using
                    the Services are between you and the advertiser, and you agree that
                    Reeflix is not liable for any loss or claim that you may have against an
advertiser.</p>

                </div>

                <p className="sec-subheading">SUPPORT</p>
                <div className="section-div ">
                    <p className="sec-para">If you have any questions, complaints or claims with respect to the
                    Website and/or Services, then such correspondence should be directed
                    to the address as given below. Reeflix Entertainment Private Limited.
The contact information – reeflixtv@gmail.com.</p>

                </div>

                <p className="sec-subheading">DISCLAIMER OF WARRANTIES</p>
                <div className="section-div ">
                    <p className="sec-para">You agree that use of the Services and the access to the Website is at
                    your own risk. The Services including the Website, the Content, the
                    video player, User Material and any other materials contained on or
                    provided through the Website are provided “AS IS” and, to the fullest
                    extent permitted by law, are provided without warranties of any kind,
                    either express or implied. Without limiting the foregoing, Reeflix
                    Entertainment Private Limited does not make any warranties of fitness
                    for
                    a
                    particular
                    purpose,
                    title,
                    merchantability,
                    completeness,
                    availability, security, compatibility or non-infringement; or that the
                    Services will be uninterrupted, free of viruses and other harmful
components, accurate, error free or reliable.</p>

                </div>

                <p className="sec-subheading">LIMITATION OF LIABILITY</p>
                <div className="section-div ">
                    <p className="sec-para">IN NO CASE SHALL REEFLIX ENTERTAINMENT PRIVATE LIMITED,
                    ITS DIRECTORS, OFFICERS, EMPLOYEES, AFFILIATES, AGENTS,CONTRACTORS, PRINCIPALS, OR LICENSORS BE LIABLE FOR ANY
                    DIRECT,
                    INDIRECT,
                    INCIDENTAL,
                    PUNITIVE,
                    SPECIAL,
                    OR
                    CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF THE
                    SERVICES OR ANY CONTENT OR MATERIAL THEREOF OR FOR ANY
                    OTHER CLAIM RELATED IN ANY WAY TO YOUR ACCESS OF THE SITE
                    OR USE OF THE SERVICES OR ANY CONTENT OR MATERIAL
                    THEREOF, INCLUDING, BUT NOT LIMITED TO, ANY ERRORS OR
OMISSIONS.</p>

                    <p className="sec-para">
                        IN ANY CONTENT OR MATERIAL, OR ANY LOSS OR DAMAGE OF ANY
                        KIND INCURRED AS A RESULT OF THE USE OF THE SERVICES OR
                        ANY CONTENT OR MATERIAL THEREOF, EVEN IF ADVISED OF
                        THEIR POSSIBILITY. WHERE THE LAWS DO NOT ALLOW THE
                        EXCLUSION
                        OR
                        CONSEQUENTIAL
                        THE
                        OR
                        LIMITATION
                        INCIDENTAL
                        OF
                        LIABILITY
                        DAMAGES,
                        IN
                        FOR
                        SUCH
                        JURISDICTIONS, REEFLIX ENTERTAINMENT PRIVATE LIMITED’S
                        LIABILITY SHALL BE LIMITED TO THE EXTENT PERMITTED BY LAW.
</p>

                </div>

                <p className="sec-subheading">INDEMNITY</p>
                <div className="section-div ">
                    <p className="sec-para">You agree to defend, indemnify and hold harmless Reeflix, its affiliates,
                    officers, directors, employees and agents, from and against any and/or
                    all claims, damages, obligations, losses, liabilities, costs or debt, and
                    expenses (including but not limited to attorney’s fees) arising from: (i)
                    Your use of and access to the Services; (ii) Your violation of any term of
                    these Terms and Conditions; (iii) Your violation of any third party right,
                    including without limitation any publicity, privacy, or intellectual
                    property right; (iv) Your breach of any applicable laws; and (v) any
                    unauthorized, improper, illegal or wrongful use of Your Account by any
                    person, including a third party, whether or not authorized or permitted
                    by You. This indemnification obligation will survive the expiry or
                    termination of these Terms and Conditions and Your use of the Service.
                    Reservation of Rights; Waiver. The Service, Software and the Digital Content embody intellectual property that is protected by law.
                    Copyright
                    owners
                    of
                    Digital
                    Content
                    are
                    intended
                    third-party
                    beneficiaries under the Agreement. Our failure to insist upon or enforce
                    your strict compliance with the Agreement will not constitute a waiver
of any of our rights.</p>

                </div>

                <p className="sec-subheading">GOVERNING LAW AND JURISDICTION</p>
                <div className="section-div ">
                    <p className="sec-para">The relationship between you and Reeflix Entertainment Private Limited
                    shall be governed by the laws of India without regard to its conflict of
                    law provisions and for resolution of any dispute arising out of your use
                    of the Services. Notwithstanding the foregoing, you agree that (i) Reeflix
                    Entertainment Private Limited has the right to bring any proceedings
                    before any court/forum of competent jurisdiction and you irrevocably
                    submit to the jurisdiction of such courts or forum and (ii) any
                    proceeding brought by you shall be exclusively before the courts at
Kolkata, India.</p>



                </div>

                <p className="sec-subheading">SEVERABILITY</p>
                <div className="section-div ">
                    <p className="sec-para">If any provision of these Terms of Use is held invalid, void, or
                    unenforceable, then that particular provision shall be considered
                    severable from the remaining provisions, and the remaining provisions
shall be given full force and effect.</p>

                </div>

                <p className="sec-subheading">CHANGES</p>
                <div className="section-div ">
                    <p className="sec-para">Reeflix reserves the right, at any time and from time to time, without
                    notice to you, to update, revise, supplement, and otherwise modify
                    these Terms of Use and to impose new or additional rules, policies,
                    terms, or conditions on your use of the Service. Any material updates,
                    revisions, supplements, modifications, and additional rules, policies, terms, and conditions (collectively referred to in these Terms of Use as
                    “Additional Terms” will be posted on the Website and user interfaces,
                    and will be effective immediately after such posting and thereafter
                    incorporated into these Terms and Conditions. Your continued use of
                    the Services will be deemed to constitute your acceptance of any and all
such Additional Terms.</p>

                </div>

                <p className="sec-subheading">SURVIVAL</p>
                <div className="section-div ">
                    <p className="sec-para">You
                    acknowledge
                    that
                    your
                    representations,
                    undertakings,
                    and
                    warranties and the clauses relating to indemnities, limitation of
                    liability, grant of license, governing law, confidentiality shall survive the
efflux of time and the termination of these Terms and Conditions.</p>

                </div>

                <p className="sec-subheading">ENTIRE AGREEMENT</p>
                <div className="section-div ">
                    <p className="sec-para">These Terms and Conditions and Privacy Policy constitute the entire
                    agreement between you and Reeflix Entertainment Private Limited
                    governing your use of the Services, superseding any prior agreements
                    between you and Reeflix Entertainment Private Limited regarding such
                    use.
</p>
                    <p className="sec-para">Last Updated: ____ March, 2020</p>
                </div>






            </div>


        </div>
    );

}

export default TermsServiceSection;
